name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate new README.md
        run: python3 generate_readme.py

      - name: Commit and push new README
        run: |
          git config user.name 'Github Actions'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: Update README with new problem'
          git push origin HEAD:main

      - name: Create new release
        run: |
          python3 release.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
